### ISSUE TITLE
Move to libp2p org and rename to go-libp2p-mplex

### ISSUE THREAD

**Issue by Stebalien** [whyrusleeping/go-smux-multiplex#9]
(but I'm too lazy to deal with this right now).

**Comment by backkem** [comment]
I suggest to also migrate to go-libp2p-core when picking this up. cc @raulk

**Comment by Stebalien** [comment]
This has been forked to https://github.com/libp2p/go-libp2p-mplex/. go-libp2p-core now includes the interfaces, but it doesn't directly depend on any of the stream multiplexers.
